### ISSUE TITLE
Release Versioning

### ISSUE THREAD

**Issue by paulfarino** [mattrothenberg/styleguide-boilerplate#13]
Alert users if they are not on the latest release of styleguide-boilerplate

Using Github's API
ex: https://api.github.com/repos/mattrothenberg/styleguide-boilerplate/releases/latest

**Psuedo**
If `tag_name` in codebase != `tag_name` of latest
show div explaining that user is not on the latest release

Thoughts on using Github tags for an initial step towards versioning and creating releases?

**Comment by paulfarino** [comment]
@mattrothenberg @abhisharma2 
Let me know your thoughts. You can pull down latest in the [releases branch](https://github.com/mattrothenberg/styleguide-boilerplate/tree/releases) (`dad093d`)
You can switch around lines [8](https://github.com/mattrothenberg/styleguide-boilerplate/blob/releases/styleguide-theme/static/js/release.js#L8) & [11](https://github.com/mattrothenberg/styleguide-boilerplate/blob/releases/styleguide-theme/static/js/release.js#L11)

**Comment by paulfarino** [comment]
Another possible implementation is to version the package.json file by using `gulp-bump`
Pull down the [latest branch](https://github.com/mattrothenberg/styleguide-boilerplate/tree/gulp-versioning)

The workflow would be to:
Use an alias to push on master such as: `gulp deploy` which would also run `gulp patch`
We would need to figure out how the best workflow and how to structure these arguments we're passing.

**Comment by mattrothenberg** [comment]
@paulfarino @abhisharma2  A release versioning strategy sounds reasonable.

I do think this warrants a larger conversation about users' workflow, and our deployment strategy in general. For instance, I'd like to know whether users are just `cloneing` our repo one time and figuring out the rest on their own? Should the styleguide be more of a scaffolding tool, like Yeoman? Should we have some kind of interactive prompt where users can choose the features that they'd like?

I would much rather us tackle something like CI first, so that we can get in the habit of automatically deploying new features to http://acme-styleguide.cfapps.io/ (i.e. your visual regression testing stuff). Hopefully, such a tool would encourage us to add more and more features / updates to the styleguide, and out of that might come the need for versioning -- so that users know where they stand.

Until then, I'm not sure what benefits versioning -- in and of itself -- really provides (besides preserving our own sanity).

Thoughts?
